Initial commit
K414BIN/MetricsManager pull request #2
Opened 2021-03-29 19:00 UTC by K414BIN

2021-04-02 13:09 UTC, Forkosigan requested changes

2021-04-02 13:09 UTC, Forkosigan commented on MainLibrary/Enums.cs
> +namespace MainLibrary
enum такие же классы как любые другие. Их также размещают в одельных файлах с именами = имени enum. Не надо все класть в один файл

2021-04-02 13:09 UTC, Forkosigan commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        public IActionResult TryToSqlLite()
А где реализованное логиование? По заданию каждый метод каждого контолера должен логировать значения своих входных параметров

2021-04-02 13:09 UTC, Forkosigan commented on MetricsAgent/Controllers/CpuMetricsController.cs
> -        [HttpGet("from/{fromTime}/to/{toTime}")]
Почему прошлые методы контроллера удалились? Это не треовалось. Их тоже надо оставить и тоже сделать так, то в них возращались данные из базы

2021-04-02 13:09 UTC, Forkosigan commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        public IActionResult TryToInsertAndRead()
не понял по какой причине здесь это метод. По заданию требуется создать таблицы в Startup (смотрите внимательно методичку).

2021-04-02 13:09 UTC, Forkosigan commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +            this.repository = repository;
приватные поля с _

2021-04-02 14:04 UTC, K414BIN commented on MetricsAgent/Controllers/CpuMetricsController.cs
> -        [HttpGet("from/{fromTime}/to/{toTime}")]
Хорошо я их верну.

2021-04-02 14:05 UTC, K414BIN commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        public IActionResult TryToSqlLite()
Я все еще пишу задание

2021-04-02 14:06 UTC, K414BIN commented on MainLibrary/Enums.cs
> +namespace MainLibrary
Я это учту на будущее, но на данный момент это я пропущу.  Мне надо доделать логирование.

2021-04-02 14:24 UTC, K414BIN commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +            this.repository = repository;
Изменил.

2021-04-02 14:24 UTC, K414BIN commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        public IActionResult TryToInsertAndRead()
Перенес в StartUp.cs

2021-04-03 05:24 UTC, K414BIN commented on MetricsAgent/Controllers/CpuMetricsController.cs
> +        public IActionResult TryToSqlLite()
Написал и отослал

2021-04-05 13:47 UTC, closed without merging

2021-04-05 13:47 UTC, K414BIN commented
Too many changes add! I dicide to create new pull request!